# Generated by Django 4.1.7 on 2023-03-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
